version: '3.8'

services: 
  petclinic:
    build:
      context: ./spring-petclinic
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql1:3306/db
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_USERNAME: root
      SPRING_PROFILES_ACTIVE: mysql   
    expose:
      - "8083"
    networks:
      - net1
    depends_on:
      - db  
  db:
    image: mysql:latest
    container_name: sql1
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 12345 
    volumes:
      - vol:/var/lib/mysql
    networks:
      - net1
    expose:
      - "3306"
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
    - "9000:80"
    depends_on:
      - petclinic
    networks:
      - net1
volumes:
  vol:
networks:
  net1: 



