global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['pet_web:8083']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
