- name: Install Docker and build images
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
        state: latest
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure app directory exists
      file:
        path: /home/vagrant/spring-petclinic
        state: directory    

    - name: Copy Dockerfile and app to hosts
      copy:
        src: /home/ahmed-taha/petclinic/spring-petclinic
        dest: /home/vagrant/spring-petclinic
      register: copy_result

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Build Docker image
      docker_image:
        name: spring-pet-image
        build:
          path: /home/vagrant/spring-petclinic/spring-petclinic
        source: build
      when: copy_result.changed

    - name: Run the container
      docker_container:
        name: spring_petclinic
        image: spring-pet-image
        state: started
        restart_policy: always
        published_ports:
          - "8080:8083"
